apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: platform-project

  sources:
    - repoURL: https://aquasecurity.github.io/helm-charts
      chart: trivy-operator
      targetRevision: 0.29.0
      helm:
        releaseName: trivy-operator
        valueFiles:
          - $values/platform/apps/trivy-operator/values.yaml

    - repoURL: https://github.com/maypi72/eu-githubops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
