apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/maypi72/eu-githubops.git
    targetRevision: main
    path: platform/apps/monitoring/prometheus
    helm:
      releaseName: prometheus
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
