apiVersion: v2
name: observability-prometheus
description: Prometheus from kube-prometheus-stack
type: application
version: 65.0.0
appVersion: 65.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 65.0.0
    repository: https://prometheus-community.github.io/helm-charts
