grafana:
  enabled: false

alertmanager:
  enabled: false

prometheus:
  enabled: true
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    queryMaxConcurrency: 20
    queryTimeout: 2m
    evaluationInterval: 30s
    scrapeInterval: 30s
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi