apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-project
  namespace: argocd
spec:
  description: "Plataforma GitOps"
  sourceRepos:
    - https://github.com/maypi72/eu-githubops.git
    - https://argoproj.github.io/argo-helm
    - https://github.io
    - https://aquasecurity.github.io/helm-charts
    - https://charts.bitnami.com/bitnami
    - https://github.com/aquasecurity/helm-charts
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
