apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform-project
  source:
    repoURL: https://github.com/maypi72/eu-githubops.git
    targetRevision: main
    path: platform/apps/monitoring/grafana
    helm:
      releaseName: grafana
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true