apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform-project
  sources:
    # 1. Chart oficial de Grafana
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.14 # Versión del chart (ajusta según necesites)
      helm:
        releaseName: grafana
        valueFiles:
          # Referencia a tu repo de Git usando el alias
          - $values-repo/platform/apps/monitoring/grafana/values.yaml

    # 2. Tu repositorio de Git para los valores
    - repoURL: https://github.com/maypi72/eu-githubops.git
      targetRevision: main
      ref: values-repo
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
