prometheus:
  enabled: false

alertmanager:
  enabled: false

prometheusOperator:
  enabled: false

grafana:
  enabled: true

  admin:
    existingSecret: grafana-admin
    existingSecretPasswordKey: admin-password

  persistence:
    enabled: true
    size: 5Gi

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: mygitops-ca
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    hosts:
      - grafana.local
    path: /
    pathType: Prefix
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.local
