apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgB0Gc0dqOwDdB7D+xny0Xw+hCxKdtNDosEEGqQBSdOKgyvY+/x4ewpybEPTumNZpHZ8ZeeOQd9bDwmtJz//BqNri/JxG0MfSCpllbrW2FIf7K0HFjERytGBColPdbvp/3XGAtnv8+xVHrmB8V6ScXxlM45N5EzNfRHgHk3e6fbqS7eohyQLrhLimYxX1/4aTYubCshU1ImsNpecA3y4oQUDP1ZhjpHIooXzqDdI1yPpIXsu+cYHO0+/aTG58xh6rp/Ql+dj8ktvDCPMc39Sx2pKdhtETu8Q+ZW1Yd2iBmVCUfdY2a7DGaxU86NaGdoWeSPLQdfnZf5XOel0cmsmL1FR8k6cg/17xg44lz0UHN88AWSB6l+12jQqkz2kfqLBLXqA4XCRez0OtZO+fCSATq/cCgv3U4bWmOXqSLhuksTJn9JxlrK3RZoscjSfYOzgfXsETXhCJj0cS48R/xXIyn3GqmYnihgyVRAQ7tLovMA0Cq3IpmZjjulwwSwalJ5MQqPbleBKYkMfBVJKR2PKIKYxvtgmWj7CuP7MuNAZxFL19ljbaG9rkZijTLYcydbEzAdQlojL9QXmyt2wjdMvIHAHrOCUXwWg7C0QfuZz3TjrQpoIDpV+k4Koe8OOgqvVAFJzApViK1NmqMOptPT+jJ5zH9LJXGaG/Qh/LKL6rp5czM2d+7bhUrzSkcvUb/D1ydXiMtjt/Lo5I2ztxy3FsWjl4UPjABvDvsEIlsGIXQpS5Ny3Q8d6v5fUv8K60vDMJlghg8/55qvi3HOXUnY=
    admin.passwordMtime: AgBJ/Wqpi/czVfHXd/feDQr4NizqdSNZnJkuiGULUZ82bDHe1lSYDxImVXyLKGxQqyXEeJlc1cGase2fNXlD07YPd6Vqp3bmCXKPuTB0QDSS8/wZr49tm483qLco+f7QieVtcE3zJadK/kO2hdDkTYtWNI9F6YS1KZxGaV8mMEbPFhNkMC5jTrjjrZ3K0wmlrhLfptybg6N8F4KrEUoJ0pfQCILP2T51tXIZPNyxiEe+rRKuZGfb9pzpsepMY0/09tJq5R8KawKU2qzRLARspQT1CT7VZ+vNHr1Z85XY3zPOUlFUdIl6vKFVAJaPl14eZWUQ7fqlsknNWCmw97BMEpl4OBE8Oqp7HHR7V1z5bRa9gjTF6/qkiVC8j+Ib7sY7REHsLxMXT2zPRPT9oKYGEVvF5ud0sV0VIK0ZDZkrTzOtRfQEY2j1uBEWedgHduWA020ZPr2uibNkYErMHGcrrE74ZEMMqYXr0ZQr+ABidkUQuFbv8JAqi2ZQGKT8rx8GHqgToW04aov/Wn5fb85PWeosEdBYyclgWQ0/LYdXBRFVEl+fe7S1Zu3EHIKkhq2LY8r1yY/YDr2/y3Wq8TdXn9cYvJeFEzEWgwltKwWbN4QM9L9xXWTu/zWRdJIlE0ksJQg2NKnOWFuWrYi1MAhp01pOzydAbZ8/Ci0KrJCNHRjytejqTc4ZsNZ9sLN7RdYSFKAgAe9t/Y5C2Fww4w==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      creationTimestamp: null
      name: argocd-secret
      namespace: argocd
    type: Opaque
---
