apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    admin.password: AgBcxRXPm5S+1XtqgoX6ZqGkE87F71dtyxaZxWX/beSuaSlUSB8zqW3NaexM52IAn3Bq+xKzW89xYYI+07YR7gaMQDfpw1ckY3fJQAa0NtX27OhQco+j8SE7PxIHHUDrdstJVm19s9hVsmf7QL8//L3XlrgPluQc8E9XAyUz+ttEjBHJeUiORM1eZ4IEAggIRZ//gbnK5fl2ZZydb3HI690Q1lEnvKd/7ogiKlMRNOM6Br5ur2IQ4t9mfkZXe898rM7ft/ovRcKnFxJBYIhRP43QX7EH603y1LJijYHlfZ6xFQFeAAcllzcmK/7vkxali2PpPpy6U9S7TbfvGNr69B/bSxRoQRrZhgcFq8Alcf/6gRrRbimtIGK57dp5tEa7xJof0heX29MA/WdOflUc8Bzb1OpoV0UrE9b6fCGkWze6LzJqeljhYi02gJKy8czXHsTB0yTet/CUtiDE9wYOUqY53Ff/Ee9SgOsOvzsksF3Yf3WGmVAzsbTdH7aEzP1BKpe5uHwzBfzlGv8xLKs75MPsHq9sAXnnUvRB4aITG6HzvHHI4hRnhAqh2BtN8uyOyh6TpWpD6ijPAFNM1eTxLtuaQ7rFO3tjIU9PWHr3J+IJp40bOsxF44pZp1AzNdfqCLHFAhd2WW+/iHOeFqG8iOqKONdtWUFoPleAVD/ZxGFCfFPzBJZP4A1juuaJUX7fmxTvDgc/bPU5jO0Pfh0x0kJUFGM+pGovSBfiuA06atpNq9qrQVTY9D3vI2ibatCR5CT1ir6yYbzvbsygGhE=
    admin.passwordMtime: AgBTLb36Tahulv1k8INunRKlVi/mYU6cYJzmbFUu3PHXSQqJcnQ20Ka0lvL9WIkhbkFeelA18xsaCCugW40ll5j97BrMGniBXrvlOlBuBA7oMuEV3Hs35OsYytAktZmrctD89H9zdTFFzq9QJPqjtWcuXyCc+U+D9guyUigjDaWruoGYcQHo4rZOIWUF6PDHPrP4KPL7XOYLE6AlUYslDBNSpHBoTM7SKBCHCiQ1JxOQcN0UoAqbHzBRLuZB47dnFM6TLXmm/Fh/FR5bzP081yf1Sea05edMmZpigxIHW3bKeYOT5ItnBpl9XX/AdrPjvHJjIgOuJe1uhC39rpfoR+D24ZjwtUEibi95lU+nBQ81D/7LfV9SW8oYI5kPP2gBukWiDKkkvqGZV8Nbj0ZiXjaXJhTxnIEzCoR8OwI6cH+by4dsG+f08jpJ9qyhc6c5zvZBevelbjdlVrSd0mLmY8ik6epZdji3peFfNAKjQ4icOLnsZOPxK4diAYBhn4Ol1lLfZX4R8wZ7PSdv1+2XTFrxUUJ5KmnVrK99ytsVhtb6PdpdK6BjnTpbd11ZP/Te7/n5OMFylNKnWn/z6ibEOBEaZR+dcfb/icmqL608D3QOgTjNb5AgI/JEO+9xQJetedkTvWbKaoE01EUISr+UNMP6oE1rvL41yXN29yH6XqX1lRxYg+L0Z4LFddWFiNZ3O3TQN8Bny6lAzIgT3Q==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-secret
      namespace: argocd
    type: Opaque
---
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
