apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgBZgqYHomE65Omg33vRIYAK1jcsYu6F94cV+kkPGsgSQTvWI8AITtX74YZCWwYGa5B9aldtI9ltK7RxerqI8HnD8OSFl39JF7Xk9vLRcX/gPKP9N6knT/A4THG8ky4SllGHPH1hM9jUbW59S1BMNqQ7/v7wqTbXsmVjnAJEEzVkf60bDP0DvKnejHaqeXSwd2FCSRp44wFk3SFrpXNWLkjkI7abx/CsogORX/RkpoPM68CPhe6iQvbv5GwMSSKNNQ2+btp5ZT34jnO+gB4QeB9DbzEJPInfbuJhTjwST1rJEI+ubzpuxVQMh/RQeYlB4/YAVtQVMe/Gxypjjp7XsQO6mNK2Tci11lFrVtAjCcAcU7PqYrT21AONlh4yUNIgXFz7vZeCn09bED5cFISDpJCujJX9u2p8UpxTCWBdqDpx+nF7kdtJqZzwmVbA1mWuzgWGZT8kNCbDxep/Hx4xPhty0Xz6E1lnRjwW1pmM2kHKB7+MwVJKF6KQILVSxGhI3o3r+cg17CnhYROBy57F+s4I6ezxQ+y8gDm+pdbSuq0RKCJ9gyzshr2ApWcmeIB64Bk2j6+YjwDGeTR+CydGSigQR3jy6PO2envo8IIKe1cbfuKK9jz0aP9b8e7CeXD5fy4U49xe3DKEQVdSNpkCKdw7WgyXgVW0PWhAPKmduD9sTFsoy1BLsLM+CSIw+qYhck9ha3xNuUWvpNhXWhN+U/d9vp7iJavBj9eXTsVijrv3USYJhRDUjS+RnGPkg/TA2NuHaSjyo488O0hMDtU=
    admin.passwordMtime: AgBotho0k/A4a4mMe5TuUGJx/6i8pEt5Sw/l5AeIuIGVlYgP7/xcDCuT7QtHKO0/cY4E2Q21rThk7796wdP1He45zDzFVFfWrfRxMkapnurgTLT8CXLmnXtk7mIJGo+kOsX5DFig+ymePNx577tOjW1xHRlbY+QA/hFxirFmul4ngrzrjPxoC+u+fECwfyKEr6fzQ0TOyWoeXpQIEEhjUAfPoH06fmKBvucxXb+APEJ6qoX2PAHkx85/XEiAGcWwazHDb/5BYxTIxqR37uSrNvdPzgH6US6ca7JogTxdSf1JlXlyHNDahIbqXV8OEhZ+owr+V5X6qBViV7reXQiONBkWGY+56e8ehwzliHUBFc2kTRYrm3Vkfxj9rRw3PxrTAwtjh9AmKC5TPQrM0N0VmGZaWm1tKW+dtpcoaBr8iea7Pl353s4LD1JWsyjTY22U15mQ+psGbBYGi35u4jHXL+DMNZmN20/rF7xewuPXRNGuUCFYQxsXaK7UXPexYsA7fS/c30RbVOW6f7fr4Z4IkomFK/pmsPJE6dbWBOqn7NUXbtwQzZPnos4owvfVVDWASym4hUMgTnQEWML/Ef+/TtNyVDhenRui9S07uPOCpUnTuFhBhpEmTY+8d4BJHsfMGqclhqtZ2ENL3bPmATw2l2nEUeCi23SW5xhDUq1DCr+PMpcjYoTF2pciL6Hf4gwBpRd/Qb8tEokdR7CR8A==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      creationTimestamp: null
      name: argocd-secret
      namespace: argocd
    type: Opaque
