grafana:
  enabled: false

prometheus:
  enabled: false

alertmanager:
  enabled: false

prometheusOperator:
  enabled: true
  crds:
    enabled: true
  admissionWebhooks:
    enabled: true
    timeoutSeconds: 10
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
