apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCVSqWUDT8kd36kyzXeWFZNe+6G+bAbj0RNNbVWsgZKkNM1E7dybtNZEkd3fDuNbjBLTUd5BWxPOcpMpw3xNXywDqJxe42X6N2Sso6B/VquQw+3w/pTK9GoKIX9sDTdwcg+P2yIXARiJlRLoSijo7nscZUxF8sAabZj67HSb07xAJQ7ZfxWZk4BauLvUEW0K2tWK84+FdxDUt70jm9s9fbYEzvCrR2xl/geyZ90Tfu1r0Di76KNqh8xTstLw6B99woxQEshQzR3H+KBJnhk8id2VYpkOvC0Bp1ExMhSvF64kcF2ZFxpCqX/cidPJqQnLw+9mKUxhPcZf1qqIgTpZT8cgMZm0bb6Ug7ZSvl2/R4MUhLsyyoyZYElk+IW9pf6/P3JQSW2NA0Gpk23ymFRxBo/wQQr2wL/8K/25PeeheAlPzGKfWDhaF6wSBuOTcfRwcbZv7/fjLyPFRyv8VQJH1FCrFUjN2Df459pnRyFFoh3ndUPCCbBr4P5XcTOUJhXmxN4qVrSvGjr/anhH3d2Ic6E+zG4Gvwx0ngplwpWA3IE+RrALFZ4TcLpADz+50C9aEdJtrmCkeumI3UE2w66iFR51XuJ+c6EZqEA3GD/hBlAqfWPTiSr7CYbSV1Ei3BxASVY/2ZWZMQoaseNZKQ3h3PJy1Q4d4aBp1Re5vRDL0ApFYsTDyh3KoHaL+iRoJ1iMlZtg83ETj2P5sJCpQ7RtIjh
    admin-user: AgCMmLqAiYIVV0puKwZ8v5KqzqLF8XxGk3V8GeiIV2n3ES2wWpjJiikKhLQAky3yMfedxRffsDtjkLy7Z2pb2VJyvjdqtrCoZsPCYP3zJaUNC0d+TEilMYNWxzG0xOgEYAMeiVxJAcjMIpXubqxs8DaOI6RT1Ug5MNYy0TXIpc1+931+tn/OarNUNaSzQTpIqFGB/eNOmY5qBd8LGxbPhC/Xh8N5hL1sCCwDk6eyLOyANLSWk/548jmglybumDqRdfsMuWarBt5WouQQcpqRNe2SccQDt/gkW2Iq/kh4jjkYtKeupy+/Kfb29ofVhbl2MM+Qvn6lkHpAxKm/BLz8efkiOJgIoNMrNmkENOIVvYWVQ1q4tG7t2wEdIBiZa3iI3XzXBy1g40so+z944T7oVheyYL4IvZtYyp0nzd/Pm8Ug1GNOYEiQu7xsJcGf+v0JNQD6DnO4+cFQW6gVk3qiOLQwXCTiCsWZvXTBiMQIV5/QRHYbZNknlHXmxJDlLq1uswq08pZ6H1SIGoyK+iRf79sumbtqoRYpTmKQECKuAYU7tuSVS+BvICWZwtUBAhyf6YKp9ls+z0VuYGAIKxPs6/yaAf8QsD1egrAXd8r+P2QQUetFxhojblDCd8tBOo1jnlYHbAhyiv7feUIRDONFnQ1zIlByqHyBSBM0jk3GI/NF9L6+/aiPpqW8oMfElRFay5Hlf4NKsA==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        meta.helm.sh/release-name: grafana
        meta.helm.sh/release-namespace: monitoring
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: Helm
      name: grafana-admin
      namespace: monitoring
    type: Opaque
---
