# Argo CD v3.3.6 | Helm chart 9.5.0
global:
  domain: argocd.local

configs:
  cm:
    url: https://argocd.local
    admin.enabled: true

  params:
    server.insecure: "false"
    reposerver.disable.tls: "true"
    application.instanceLabelKey: argocd.argoproj.io/instance
    applicationSetController.enable.progressive.syncs: "true"

dex:
  enabled: false

redis:
  enabled: true

controller:
  reposerver:
    strictTLS: false
  replicas: 1
  dynamicClusterDistribution: false
  enableMultiSource: true
  resources:
    requests:
      cpu: 150m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi

server:
  replicas: 1

  extraEnv:
    - name: ARGOCD_SERVER_REPO_SERVER
      value: argocd-repo-server:8081
    - name: ARGOCD_REPO_SERVER_STRICT_TLS
      value: "false"
    - name: ARGOCD_REPO_SERVER_TIMEOUT_SECONDS
      value: "60"

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

  service:
    type: ClusterIP
    https: true   # 🔥 CLAVE: habilita el puerto 443 del Service
    servicePorthttps: 443
    servicePorthttp: 80

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "mygitops-ca"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - argocd.local
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.local

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

applicationSet:
  replicas: 1

notifications:
  enabled: false
