# Argo CD v3.3.6
# Helm chart 9.5.0
# k3s + Calico
# TLS terminado en Ingress (nginx)
# repo-server SIN TLS interno

global:
  domain: argocd.local

configs:
  cm:
    url: https://argocd.local
    admin.enabled: true
    application.instanceLabelKey: argocd.argoproj.io/instance
    applicationSetController.enable.progressive.syncs: "true"

  params:
    # UI / API sin TLS interno
    server.insecure: "true"
    # ⚠️ OJO: NO existe reposerver.disable.tls en este chart → eliminado

dex:
  enabled: false

redis:
  enabled: true

controller:
  replicas: 1
  extraArgs:
    - --repo-server-plaintext
  resources:
    requests:
      cpu: 150m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 760Mi

server:
  replicas: 1
  extraArgs:
    - --repo-server-plaintext
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: mygitops-ca
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - argocd.local
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.local

repoServer:
  replicas: 1
  extraArgs:
    - --disable-tls
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi

applicationSet:
  replicas: 1

notifications:
  enabled: false
