# Argo CD v3.3.6 – Helm chart 9.5.0
# k3s + Calico – TLS solo en Ingress

global:
  domain: argocd.local

configs:
  cm:
    url: https://argocd.local
    admin.enabled: true

  params:
    # UI / API sin TLS interno (Ingress se encarga)
    server.insecure: true

    # 🔴 CLAVE: desactivar TLS interno del repo-server
    reposerver.disable.tls: "true"

    # Opcional pero recomendable para entornos pequeños
    applicationsetcontroller.enable.progressive.syncs: "true"

configuration:
  params:
    application.instanceLabelKey: argocd.argoproj.io/instance

dex:
  enabled: false

redis:
  enabled: true

controller:
  replicas: 1
  resources:
    requests:
      cpu: 150m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 760Mi

server:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: mygitops-ca
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - argocd.local
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.local

repoServer:
  replicas: 1

  # Probes HTTP estándar (vuelven a funcionar al quitar TLS)
  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    httpGet:
      path: /healthz?full=true
      port: 8084

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    httpGet:
      path: /healthz
      port: 8084

  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  replicas: 1

notifications:
  enabled: false