# Configuración optimizada para K3s en Laboratorio
controller:
  kind: DaemonSet
  hostNetwork: false
  dnsPolicy: ClusterFirst
  hostPort:
    enabled: true
  service:
    type: ClusterIP
  admissionWebhooks:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 90Mi