apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-alertmanager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform-project

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 84.2.1
      helm:
        releaseName: monitoring-alertmanager
        valueFiles:
          - $values/platform/apps/monitoring/alertmanager/values.yaml

    - repoURL: https://github.com/maypi72/eu-githubops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
